---
title: "Adrian"
output: html_notebook
---

Install packages
```{r}
#install.packages("tidyverse")
#install.packages("jsonlite")
#install.packages("devtools")
#devtools::install_github("brooke-watson/BRRR")
```


Load libraries
```{r}
library(tidyverse)
library(jsonlite)
library(BRRR)
library(tidyr)
```


Messing around with BRRR
```{r}
#skrrrahh()
#defaultSounds <- list(1:52)
#customSounds <- list("http://www.migossoundboard.com/audio/takeoffPowPow.wav", "http://www.migossoundboard.com/audio/quavoRahw.wav", "http://www.migossoundboard.com/audio/takeoffChirp.wav")
#sounds <- list(defaultSounds, customSounds)
#skrrrahh(sample(sounds,1))
```


Import JSON data to a datatable
```{r}
<<<<<<< HEAD
data <- fromJSON("data/train.json")
=======
data <- fromJSON("train.json")
>>>>>>> f1a0f5cf09d91d6d26c88d4edd1818b607c25ef4
head(data)
```


Split ingredients column into seperate rows with duplicated id and cuisine values (make data long)
```{r}
#using the unnest function from tidyr does this very well
dataLong <- unnest(data, ingredients)
head(dataLong)
```


Spread ingredients across columns to make dummy variables (make data wide)
```{r}
dataTidy <- dataLong %>%
  mutate(yesno = 1) %>%
  distinct %>%
  spread(ingredients, yesno, fill = 0)

head(dataTidy)
```


Begin to inspect the data
```{r}
levels(as.factor(dataTidy$cuisine))
```

Exploring text clustering

```{r}
library(stringdist)
library(RCurl)
```


```{r}
foodSmall <- dataLong[1:50,3]
head(foodSmall)
length(unique(foodSmall))
```

```{r}
uniqueSurg <- unique(as.character(foodSmall))
distanceSurg <- stringdistmatrix(uniqueSurg,uniqueSurg,method = "jw")
rownames(distanceSurg) <- uniqueSurg
hc <- hclust(as.dist(distanceSurg))
plot(hc)
rect.hclust(hc,k=20)

#dfClust <- data.frame(uniqueSurg, cutree(hc, k=400))
#names(dfClust) <- c('Surgery Name','cluster')
#plot(table(dfClust$cluster))
```

